cloud:
    aws:
        credentials:
            access-key: ASIAXXEC3QIWSNQQBUVP
            secret-key: bH0Ewx6Mtz0WYzvq/Z9o6IINUJNc8+51qqxMkvE5
            session-token: IQoJb3JpZ2luX2VjENj//////////wEaCXVzLXdlc3QtMiJHMEUCIAhStkd/iPZbVXwp5lT3vAcp8OZtgrM9ct2xWBjzn+NHAiEApjT9XphHrUQ0ybaXYPem94HUIMlaLD+xYI8+qyWDcMwquAIIsf//////////ARADGgw1MzA3MDI4OTM2MTMiDCck3UdD8gcm9+jHjSqMAvCXP+1/skFKc2p41vYpSFI7x7UL1j7bzItgi2ZDfYkA4HLVvp/IaChrQEsoDChd3DSDmW9qIfCYu8ri/SJk10NT/ptG0HCv1hU1rlvRdtvZzwFZUE01sVOPC3mIt0xXa7q9XIy7MiWQMLU+IF/I3S2N/6onm7y/LXGgmOjKT21qXKlmsF2J9Zdb1yp4OAwCNcBngQdSeyroK6Ei+b/xxLRVi3FzySa0ZKYWgCOH/LQrBueg5BsWf8u72TFisM2hNlPtc8Ibzrf9bjVV2aA/y0/4WvVFlVl7cnaFzeWyW1kKaYiFoZ5ZgunGYuItBwCb/zDOZUufdSuGXm+w40Rhb5P1xWtG2xoAI7PUooswjuadwgY6nQGs8q5LUpa9/kxjwqF3aCPV+vwXVZLLci1QmHiZICB4UeXOnqTLuHhZ5nOM6gnsptNuyR86H+v1/UtQQIN3jKIjX8VClf9NYaEykE3UXAJQrOR0OUiTkF8atBVCQ73+RSL1PHyrvJjYwebetRKj8WXGCjdBnXFH5fCsByGD5YhVYoAzEyXikj4TBY5lg47+duktIs5kAnIvv6Uv+dwB
        region:
            static: us-east-1
        stack:
            auto: false